### ISSUE TITLE
Question - Deploying with github.io instead of vercel

### ISSUE THREAD

**Issue by jnyfah** [sandypockets/nextjs-blog-starter#2]
Hi, I really love your starter blog, thanks for designing this 
I have a question, can I deploy this on github.io instead of using vercel app?

**Comment by sandypockets** [comment]
Hey, thank you! 

I don't think so. I haven't used GitHub Pages myself, but from what I understand they are completely static, and don't have access to Node.js/can't run any server-side code. 

You might be able to workaround that by [exporting the starter blog as static HTML](https://nextjs.org/docs/advanced-features/static-html-export). However this starter does use some of the [unsupported features for static HTML export](https://nextjs.org/docs/advanced-features/static-html-export#unsupported-features); so you'd need to disable the [Image optimization](https://nextjs.org/docs/advanced-features/static-html-export#unsupported-features) and rewrite the Contact page so that the email it sends does't use [API routes](https://nextjs.org/docs/api-routes/introduction). 

Alternatively, you aren't limited to just using Vercel. Platforms like [Netlify](https://www.netlify.com/), and [Heroku](https://heroku.com/) would work too.

**Comment by jnyfah** [comment]
Okay, will check it out 
Thanks a lot!
